name: flutter_sign_up
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.17
  lottie: ^2.2.0
  flutter_otp_text_field: ^1.1.1
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  get: ^4.6.5
  cloud_firestore: ^4.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/logo/quark_logo.png
  image_dark: assets/logo/quark_logo.png

android_12:
  image: assets/logo/quark_logo.png
  image_dark: assets/logo/quark_logo.png
  icon_background_color: "#f7f6f1"
  icon_background_color_dark: "#272727"

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/chameleon_image.svg
    - assets/logo/quark_logo.png
    - assets/images/welcome_screen_images/welcome_top.svg
    - assets/lottie/login_lottie.json
    - assets/logo/google_svg.svg
    - assets/lottie/signup_lottie.json
    - assets/lottie/forgot_password.json

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
