// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtsbCCapHbWYMsKisYPgkvr6bVutkur4Q',
    appId: '1:863682331832:android:e4eedde2311b4f0a43604d',
    messagingSenderId: '863682331832',
    projectId: 'flutterlogindemo-fee56',
    storageBucket: 'flutterlogindemo-fee56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF9_beQU2xyOCrUkp_nZyQKh8omDZV8Xc',
    appId: '1:863682331832:ios:ba959adf7261cbe443604d',
    messagingSenderId: '863682331832',
    projectId: 'flutterlogindemo-fee56',
    storageBucket: 'flutterlogindemo-fee56.appspot.com',
    androidClientId: '863682331832-5nvcr4l5un39of3euhght1eca2l1iugv.apps.googleusercontent.com',
    iosClientId: '863682331832-24qk93idddk8gg502q4qg5live3kjkuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSignUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF9_beQU2xyOCrUkp_nZyQKh8omDZV8Xc',
    appId: '1:863682331832:ios:ba959adf7261cbe443604d',
    messagingSenderId: '863682331832',
    projectId: 'flutterlogindemo-fee56',
    storageBucket: 'flutterlogindemo-fee56.appspot.com',
    androidClientId: '863682331832-5nvcr4l5un39of3euhght1eca2l1iugv.apps.googleusercontent.com',
    iosClientId: '863682331832-24qk93idddk8gg502q4qg5live3kjkuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSignUp',
  );
}
